@server=https://evc3christianpancich.onrender.com
@api={{server}}

###
GET {{api}}/categorias
###
POST {{api}}/categorias
Content-Type: application/json

{"nombre": "Instrumento de Cuerda"}
################ Instrumentos: ################
###
GET {{api}}/instrumentos
###
POST {{api}}/instrumentos
Content-Type: application/json

{"nombre": "Guitarra", "categoria":"http://localhost/api/ec3/categorias/2"}
###
GET {{api}}/instrumentos/2/categoria
###
GET {{api}}/instrumentos?sort=nombre,desc